remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
title: [TaskMaster User Guide]
description: [TaskMaster is a task tracker chatbot that can help keep track of todos, deadlines and events via a Command Line Interface (CLI)]
